# Generated by Django 5.2.7 on 2025-10-30 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('tarif_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibleVecules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReservation', models.DateField()),
                ('heurDebut', models.TimeField()),
                ('heurFin', models.TimeField()),
                ('Vehicules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibe', to='vehicules.vehicules')),
            ],
        ),
    ]
