# Generated by Django 5.2.7 on 2025-11-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteVehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='vehicules.vehicules')),
            ],
        ),
        migrations.DeleteModel(
            name='DisponibleVecules',
        ),
    ]
