# Generated by Django 5.2.7 on 2025-11-03 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_disponibilitevehicules_delete_disponiblevecules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
