# Generated by Django 5.2.7 on 2025-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_utilisateur',
            field=models.CharField(choices=[('Entreprise', 'Entreprise'), ('Particulier', 'Particulier')], default='Particulier'),
        ),
    ]
